signup
amoon46/TwitterClone pull request #1
Opened 2022-04-13 02:54 UTC by amoon46

ユーザー登録機能作りました

2022-04-13 12:36 UTC, TAK848 requested changes
オートフォーマットをしてくれたりpipenvを使ってくれたりと，環境構築などなど…とても丁寧でgoodです！！
以下に何点かコメントしましたので確認をお願いします！

追加で，`user/tests.py`にテストを書いてください。
最低限のテスト項目として，Signup時の，
- 正常にデータが入力された時のステータスコードと，ユーザーが作成されたか（前ユーザー数をカウントなどでOK）
- 異常なメアドやパスワード（[settings.py](https://github.com/amoon46/TwitterClone/blob/feature/signup/config/settings.py#L90)で設定されている，メアドと似ている・短すぎる・一般的すぎる・数字のみをそれぞれ）が入力されたときのステータスコードと，エラーメッセージが存在するか，ユーザーが間違って作成されていないか
- パスワードの確認フィールド（password2）をもし追加する場合は，違うパスワードを入力したときのステータスコード・エラーメッセージ・ユーザーが作成されていないこと

はチェックするようにしてください！

最近でた[テスト仕様](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=842149650)や[テンプレート](https://github.com/shinonome-inc/backend-final-assignment/blob/main/accounts/tests.py)を用いてもらってもOKです！

2022-04-13 12:36 UTC, tak848 commented on Pipfile
> +autopep8 = "*"
👍

2022-04-13 12:36 UTC, tak848 commented on config/settings.py
> +        'DIRS': [os.path.join(BASE_DIR, 'templates')],
Django3.1から，Pathlibが使われるようになり，os.path.joinが不要になりました。
```suggestion
        'DIRS': [BASE_DIR / 'templates'],
```
のみでOKで，osライブラリのインポート無しで完結できます。
[こちら](https://qiita.com/TomoyaT_qq/items/167d1105ddda0205d0ed)も参考にしてみてください。

2022-04-13 12:36 UTC, tak848 commented on config/settings.py
> +STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
同様にPathlibで書いてみましょう！

2022-04-13 12:36 UTC, tak848 commented on templates/user/home.html
> +
2行不要な空行があるので消しときましょう！

2022-04-13 12:36 UTC, tak848 commented on user/admin.py
> +from .models import User
ローカルなアプリケーションのimportは1行追加で開けるとさらにgoodです！
https://pep8-ja.readthedocs.io/ja/latest/#import も参考にしてみてください。

autopep8に加えて，isortというライブラリを用いるとこちらも自動化できるので試してみてください！
```suggestion
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from .models import User
```

2022-04-13 12:36 UTC, tak848 commented on user/forms.py
> +from user.models import User
```suggestion
from .models import User
```
にしましょう
ついでに並び替えと空行もお願いします！

2022-04-13 12:36 UTC, tak848 commented on user/views.py
> +# Create your views here.
消しておきましょう！

2022-04-13 12:36 UTC, tak848 commented on user/views.py
> +    # プロジェクトのURLConf(url.py)が読み込まれる前に、URLの返す
```suggestion
    # The form class to instantiate.
    form_class = SignUpForm
    # プロジェクトのURLConf(url.py)が読み込まれる前に、URLの返す
    success_url = reverse_lazy('user:home')
```
コメントは対象箇所の上に書くのが一般的な気がします

2022-04-13 12:36 UTC, TAK848 commented on templates/user/signup.html
> +  </form>
このままだとサーバー側でのバリデーション失敗時にエラーが出ないので，追記してください！
各fieldのエラー＋nonfielderrorも忘れずに！

2022-04-13 12:36 UTC, TAK848 commented on templates/user/signup.html
> +  <form role="form" action="{% url 'user:signup' %}" method="post" enctype="multipart/form-data">
`multipart/form-data`もDjangoは対応していますが，デフォルトの`application/x-www-form-urlencoded`で問題ないです
```suggestion
  <form role="form" action="{% url 'user:signup' %}" method="post">
```

2022-04-13 12:36 UTC, TAK848 commented on user/models.py
> +        '君の名は。'),)
多分オートフォーマットで途中で改行されたのだと思うのですが，かえって見辛くなってしまっているので，中途半端に改行されてしまった時は1つ1つ改行するのがおすすめです。introductionも同様です
```suggestion
    nickname = models.CharField(
        verbose_name='ニックネーム',
        max_length=10,
        blank=True,
        null=True,
        help_text=('君の名は。'),
    )
```

2022-04-13 12:36 UTC, TAK848 commented on user/models.py
> +        verbose_name_plural = 'users'
Metaはクラスの一番上にある方がみやすい気がします

2022-04-13 12:36 UTC, TAK848 commented on user/models.py
> +"""
メモだと思いますが，消しておきましょう

2022-04-13 12:36 UTC, TAK848 commented on user/forms.py
> +    password2 = password1
passwordをCharFieldにしてしまったことで，[settingsで定義した](https://github.com/amoon46/TwitterClone/blob/feature/signup/config/settings.py#L90)，既存だったバリデーションが効かず，パスワードが「a」一文字などでも通過してしまっています。

もしこだわりがなければデフォルトのpassword1とpassword2を用いることをお勧めします。

パスワードの入力を1つにする場合は，少なくともpassword1はそのままにするなどしてバリデーションは効くように修正してください。（例えば[こんなふう](https://stackoverflow.com/questions/66475809/how-to-remove-password-confirmation-field-in-django-usercreationform)にしたり，あるいはclean_password2をそのまま通過させるようにしたり）

2022-04-13 12:56 UTC, TAK848 commented on templates/user/signup.html
> +  <form role="form" action="{% url 'user:signup' %}" method="post" enctype="multipart/form-data">
追記: [参考](https://developer.mozilla.org/ja/docs/Web/HTML/Element/form#attr-enctype)

2022-04-21 06:31 UTC, amoon46 commented
質問です。
Signup機能で登録する際にメールアドレスに変更しusernameを外したのですが、将来的にfollow機能を実装することを考えるとusernameをモデルに組み直した方が良いのでしょうか？

2022-04-21 13:13 UTC, TAK848 requested changes
良い感じです👍

主にテストに関してコメントしました！
確認お願いします！

次回以降一応，テスト作成・変更時はテストに成功したスクリーンショットなどを添付しておいてもらえると嬉しいです！

2022-04-21 13:13 UTC, tak848 commented on user/tests.py
> -# Create your tests here.
`user/test.py`に中身が移動してしまっているので，このファイル（`user/tests.py`）に中身を書くようにしてください！

2022-04-21 13:13 UTC, tak848 commented on user/test.py
> +class TestFailSignUpView(TestCase):
`TestSignUpView`に含めましょう！
（各テストに，`test_success_...`や`test_failure_...`のように書いているのでそこで判別可能）

2022-04-21 13:13 UTC, tak848 commented on templates/user/base.html
> +                <a class="nav-link" href="/">Home</a>
```suggestion
                <a class="nav-link" href="{% url 'user:home" %}>Home</a>
```
のようにテンプレートでも参照できます。変更に備えてこうしておくのがおすすめです！（前回のコメント抜けです，すみません）

2022-04-21 13:13 UTC, tak848 commented on templates/user/base.html
> +                <a class="nav-link" href="/signup">Signup</a>
Djangoにおいてはパスの最後に`/`をつける（トレイリングスラッシュといいます）のが基本なので，後ろのスラッシュはそのままつけたままでOKです！
この辺も含めてurls.pyにあわせてやってくれるので，`{% url ...`に変えておきましょう！

2022-04-21 13:13 UTC, tak848 commented on user/urls.py
> +    path('', views.HomeView.as_view(), name='home'),
前回のレビュー抜けですが，`home`に関してはuserに特化したページではないので，`config/urls.py`にそのまま書いた方が綺麗です
参照方法も，user:homeと不自然だったのがhomeだけでOKになり自然になります

（※その時views.pyを足したくなければさらに[こんな記法](https://qiita.com/ytyng/items/7cb3c3a5605974151678#1-urls-%E3%81%A7-as_view-%E3%81%AB%E5%BC%95%E6%95%B0%E3%82%92%E4%B8%8E%E3%81%88%E3%82%8B%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3)もできます）
（※この観点からすると，お任せしますが，用途によってはtemplate内のhtml（homeなど）も移動した方がわかりやすいかもしれません。）

2022-04-21 13:13 UTC, TAK848 commented on user/test.py
> +        self.response_post = self.client.post(self.url_signup, self.data)
テストのsetUpは，`test_**`メソッドが呼ばれるたびに毎回呼ばれます。そのため関係のないテスト実行時も繰り返しリクエストをかけてしまっています。
* client.getやpostは基本メソッド内に書きましょう。
* postのデータなども，それぞれの関数に固有のものであればそれぞれのメソッドに書いた方が見通しが良くなると思います。
* url_homeやurl_signupといった共通のデータはそのままsetUpに残しておいてOK！

公式ドキュメントや[こちらのページ](https://qiita.com/okoppe8/items/eb7c3be5b9f6be244549#%E5%87%A6%E7%90%86%E3%81%AE%E6%B5%81%E3%82%8C)などからテストの流れを掴んでみてください。

2022-04-21 13:13 UTC, tak848 commented on user/test.py
> +        # self.assertEqual(user_object.password, self.data['password1'])
👍
生のパスワードは保存されていないので，そのままの値と比較することはできません。その通りです。
テストの加減は難しいですが，パスワードまで丁寧にチェックしなくてもOKですのでそのまま消してもらって大丈夫です！

詳しいDjangoのパスワード保存方法は，[公式doc](https://docs.djangoproject.com/en/4.0/topics/auth/passwords/)なども，興味があれば参考にしてみてください。（キーワード:ソルト・ハッシュ化・ストレッチングなど）

2022-04-21 13:13 UTC, tak848 commented on user/test.py
> +    def setUp(self):
上記のコメントと同様，メソッド特有のデータやリクエストは各メソッドに分けましょう

2022-04-21 13:13 UTC, TAK848 commented on user/test.py
> +        self.assertTrue(form.errors)
form.errorsだけだとエラーの幅が広すぎるので，ちゃんとターゲットの場所にエラーが出ているかを確認したほうが良いと思います。
具体的には，場所を絞れないエラーは`non_field_errors`に，それぞれのフィールドのエラーはそれぞれのフィールド名（例えばemail，password1など）に格納されます。
ここまで絞ってassertTrueしてみてください！

2022-04-21 13:24 UTC, TAK848 commented
コメントを見失ってしまったんですが，メールに残っていたので一応，usernameが必要かどうかについて。
結論から言うと無くても問題ないです。

対象のユーザーを自分がフォローしたい！となった時に，どのユーザーをフォローしたいかさえ特定できればOKです。
usernameをユニーク（重複がない）に作成していれば，もちろんこのユーザーネームも使用できます。

usernameを使用せずとも，Djangoではデフォルトで各モデルのオブジェクトごとに連番のID（データベース上ではprimary keyなどと呼ばれる）が振られています。このIDもユニークに振られています。
それゆえ，この番号のIDのユーザーをフォローしたいんだ！みたいなリクエストを現状でも作成できるのでどちらでもOKです。

（ちなみにemailもユニークだけど，これを識別に使用するのは個人情報的にも不適切だと思います）

2022-04-21 13:56 UTC, amoon46 commented on user/tests.py
> -# Create your tests here.
ここの修正がわからないので、もう少し詳しくお願いします。

2022-04-21 14:04 UTC, amoon46 commented on user/test.py
> +class TestFailSignUpView(TestCase):
ここのclassを同一にすると、postで失敗したことを確認する関数でself.assertFalse(User.objects.exists())の結果がerrorになってしまうため、別々分けたのですが同一にした方がいいでしょうか？

2022-04-21 16:00 UTC, amoon46 commented on user/urls.py
> +    path('', views.HomeView.as_view(), name='home'),
とりあえず、config/urls.pyにhomeを移動しましたが、Twetterの機能を考えると最終的にはtweet（アプリ）のtop画面に持ってきてもいい気がしますがどうでしょうか？

2022-04-21 16:26 UTC, amoon46 commented on user/test.py
> +        self.assertTrue(form.errors)
"このフィールドを入力してください"というエラー以外のpasswordに関係するエラー分は場所を絞るためのフィールドがpassword2だったのですが、これはformに記入したものsubmitする際に確認する項目になるためという認識であっているでしょうか？
また、念の為print(form.errors)でエラーメッセージを出力した上で、asserTrueを作成しました。

2022-04-21 16:43 UTC, amoon46 reviewed
![test review detail](https://user-images.githubusercontent.com/74179935/164509998-db0285c9-4da3-4864-868f-540990fad029.png)

2022-04-21 22:24 UTC, TAK848 commented on user/tests.py
> -# Create your tests here.
`tests.py`が`test.py`となっていたので，`tests.py`に直してね！と言う意味です。
`tests.py`は最初から無くなっていましたね…こちらの説明が半分おかしかったです，すみません！

2022-04-21 22:35 UTC, TAK848 commented on user/tests.py
> -# Create your tests here.
あと現状，testsフォルダにtest.pyが入っていますが，このままだと，
`python manage.py test`
単体で実行されません。

* 原則として，テストのファイルは，アプリの直下に`tests.py`と言う名前で配置するのが慣習です。（違うファイル名でもテストはされますが。）
  <img width="221" alt="Screen Shot 2022-04-22 at 7 28 42" src="https://user-images.githubusercontent.com/41906969/164561861-40e9cb98-2485-487d-ab73-26798e4ba703.png">

* もしフォルダ分けをしたままにしたい場合は，`tests`フォルダに`__init__.py`をからのファイルで作成してください。
  <img width="227" alt="Screen Shot 2022-04-22 at 7 27 53" src="https://user-images.githubusercontent.com/41906969/164561763-1a78a4e7-7f7e-4e96-84fe-7a9110fe60b7.png">

※2つ目の，フォルダを作成する書き方は，tests対象をviewやformごとに分割したい時に使うことがあります。（serializersは外部ライブラリによるものなので気にしないでください）
  <img width="196" alt="Screen Shot 2022-04-22 at 7 30 21" src="https://user-images.githubusercontent.com/41906969/164562132-53cc2896-1590-4a68-a434-38c62ef688aa.png">

2022-04-21 22:35 UTC, TAK848 commented on user/urls.py
> +    path('', views.HomeView.as_view(), name='home'),
鋭い質問ですね！
正解はないと思います。

tweetアプリはconfig.urlsでは`tweets/`パスなどで一括でルーティングする設計が多いと思いますし，homeを入れるにちょっとurlsが汚くなってしまう感じがします。
意味的な分類とurlの割り振りのことを考えて，僕だったらの話ですが，新たに`index.html`などの基本ページを表示するための，twitterみたいなアプリを作成し，twitter:homeみたいな感じで参照できるようにするかなと思います。
自由にやってみてください！

2022-04-21 22:39 UTC, TAK848 commented on user/test.py
> +class TestFailSignUpView(TestCase):
多分，以前の`setUp`での処理が干渉していたのかなと思いますが，現状だと統合してみてもテストは成功しそうです！
<img width="453" alt="Screen Shot 2022-04-22 at 7 37 23" src="https://user-images.githubusercontent.com/41906969/164562716-8a6ef71b-4cdc-4cf0-a56b-3af0cf461662.png">

もし質問の趣旨を捉え違えていたらコメントください！

2022-04-21 22:41 UTC, TAK848 commented on user/test.py
> +class TestFailSignUpView(TestCase):
（もちろん統合は絶対ではないので，失敗と分けた方が良い！と言うことであれば，僕としてもそのままでもOKです）

2022-04-21 22:55 UTC, TAK848 commented on user/test.py
> +        self.assertTrue(form.errors)
結論から言うと，UserCreationFormでは，パスワードのバリデーションエラーは`password2`に出てくる仕様になっていますね。
「formに記入したものをsubmitする際に確認する項目になるため」かは，僕からはわからずなんとも言えません…ごめんなさい！
作った人が，バリデーションエラーはpassword2に表示するように動くようにした，と言うことだと思います。

参考に，[stackoverflow](https://stackoverflow.com/questions/65863073/moving-password-validation-errors-for-django-usercreationform-from-password2-t)で，password2にバリデーションエラー表示されて気持ち悪い！と言う話があったのでシェアしておきます

2022-04-21 23:04 UTC, TAK848 reviewed
ほぼ良い感じです！
以前のコメントの返信のチェックと，以下のコメントのチェックお願いします！

2022-04-21 23:04 UTC, tak848 commented on templates/user/base.html
> +<!doctype html>
user/baseも全体に共通部分なので，userの中に入れとくよりは，外に出す方が良さそうですね

（あるいは，urlの部分の[質問の返答](https://github.com/amoon46/TwitterClone/pull/1#discussion_r855641333))に書いたように，twitterアプリなどを作って，twitterフォルダに入れるとか）

2022-04-21 23:04 UTC, tak848 commented on user/tests/test.py
> +        )
2つ目のチェックが1つ目を完全に含んでいるので，どっちかだけでOKです！
* 全体との統一を図るなら125行目のみ
* パスワードに関してはエラー内容まで細かくチェックするなら126-128行目のみ

以下同様です

2022-04-22 03:42 UTC, amoon46 reviewed
<img width="1440" alt="test_rereview" src="https://user-images.githubusercontent.com/74179935/164591866-0060eca8-32c2-4f11-bcdb-144ad7bc1555.png">

2022-04-22 04:29 UTC, TAK848 approved these changes
LGTM!!

.DS_storeが紛れているので，
https://www.toptal.com/developers/gitignore/api/macos
とかをgitignoreに追加して，キャッシュから削除だけお願いします！

2022-04-22 15:42 UTC, Akinori13 requested changes
とてもいいです！少しだけコメントしました。
- .DS_Storeを消去するようにお願いします

2022-04-22 15:42 UTC, Akinori13 commented on config/settings.py
> +AUTH_USER_MODEL = 'user.User'
いいですね！！ここだと探しづらいのでもう少し下の方にコメント付きで記載してもいいと思います！

2022-04-22 15:42 UTC, Akinori13 commented on templates/twitter/base.html
> +<html lang="en">
```suggestion
<html lang="ja">
```

2022-04-22 15:42 UTC, Akinori13 commented on templates/twitter/base.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorig
Good！

2022-04-22 15:42 UTC, Akinori13 commented on templates/twitter/base.html
> +    <title>Hello world</title>
せっかくなのでタイトルも可変にしましょ！

2022-04-22 15:42 UTC, Akinori13 commented on templates/twitter/home.html
> +
必要ない空行は消しましょう！

2022-04-22 15:42 UTC, Akinori13 commented on templates/user/signup.html
> +          <small style="color: grey">{{ field.help_text }}</small>
任意ですが、Bootstrapでもカラー付与できます。

2022-04-22 15:42 UTC, Akinori13 commented on templates/user/signup.html
> +          <small style="color: grey">{{ field.help_text }}</small>
https://getbootstrap.com/docs/5.1/utilities/colors/

2022-04-22 15:42 UTC, Akinori13 commented on twitter/urls.py
> +from . import views
ここは一行空けてもいいでしょう
```suggestion
from django.urls import path

from . import views
```

2022-04-23 06:01 UTC, Akinori13 reviewed
DS_Storeが消えていないので確認をお願いします
https://www-creators.com/archives/6144#1git_add

2022-04-24 13:10 UTC, Akinori13 commented
LGTM

2022-04-24 13:10 UTC, Akinori13 approved these changes

2022-04-24 13:10 UTC, merged