first commit
amoon46/TwitterClone pull request #2
Opened 2022-05-04 04:46 UTC by amoon46

ログイン、ログアウト、プロフィール機能を実装しました。

2022-05-04 04:49 UTC, amoon46 commented
テスト機能の部分でsession keyがいまいち分からず実装できませんでした。また、user/viewの部分のLoginRequiredMixinによるものなのか、テスト部分でresponse.codeが一致せず上手くいっていません。

2022-05-04 09:09 UTC, TAK848 requested changes
お疲れ様です！細かい気配りができていてとてもgoodです！細かな点についてコメントしましたので確認お願いします！

* Pull requestのタイトルがfirst commitだと何のことだかわからないので，最低限機能名を書くなどして内容がわかるように変更してください！
* 前回のPRでなぜか`.gitignore`から`.DS_Store`が削除されてしまっていて，色々な場所に混入しているので，改めて`.gitignore`に追記した上で，cacheからも削除してください！

## テストの質問について
ログインのテストのヒントを以下に記します！（不明点あれば返信してください！）
### ユーザーがそもそも存在しない
Djangoでは，テスト時のDBはテスト用のものを別で毎回作成して実行しています。Signupのテストで作成したからSigninのテストでユーザーが存在する，ということもありません。

現状だと，ログイン対象のユーザーが（テスト用の）DBに存在していません。

改めて，[テストのフローの参考記事](https://qiita.com/okoppe8/items/eb7c3be5b9f6be244549#%E3%83%86%E3%82%B9%E3%83%88%E3%81%AE%E5%8B%95%E4%BD%9C)（や公式doc）を参照してテストの流れを確認しながら，
テスト用のユーザー作成（create_user）を，setUpもしくはsetUpClass内で実行し，予めユーザーを作成してみてください。

### postするデータの「何か」がおかしい
2つ目のヒントは，
```python
self.response_post = self.client.post(self.url_login, self.data)
```
の後に，
```python
print(self.response_post.context.get('form').errors)
```
と書き足してテストを実行してみると，発見があるはずです！やってみた上で，修正してみてください！
それでもわからなければ遠慮なく教えてください！
## テストがうまくいくようになったら
* 成功したらテストのスクショをPRに貼ってください
* profile updateのテストも，signinのテストを理解すれば可能だと思うので，postしたデータがきちんと更新されるかのテストを書いてみてください！

2022-05-04 09:09 UTC, tak848 commented on config/settings.py
> +LOGOUT_REDIRECT_URL = '/login/'
ここでも，`appname:index`の形式が使えるので，`'user:login'`や，`'twitter:home'`を使いましょう

2022-05-04 09:09 UTC, tak848 commented on templates/user/login.html
> +
最後の空行は1行だけでOK！2行になってます！
profile.htmlも同様

2022-05-04 09:09 UTC, tak848 commented on templates/user/navbar.html
> +
空行1行でよさそう

2022-05-04 09:09 UTC, tak848 commented on user/forms.py
> +from django import forms
使っていないimportは消しましょう

2022-05-04 09:09 UTC, tak848 commented on user/forms.py
> +            field.widget.attrs['placeholder'] = field.label
既存のものをできるだけ使用しつつplaceholderをうまく足していてgood👍👍👍

2022-05-04 09:09 UTC, tak848 commented on user/forms.py
> +from django.contrib.auth.forms import AuthenticationForm
これ1行にできます！
```suggestion
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
```

2022-05-04 09:09 UTC, tak848 commented on user/models.py
> +    followees = models.ManyToManyField('self', blank=True, symmetrical=False)
この先の機能なので今回のPRには含めない方が，後から見返す観点や，レビューの都合的にも嬉しいです！

2022-05-04 09:09 UTC, tak848 commented on user/views.py
> +        return super().form_invalid(form)
検証に使ったのかなと思いますが，消しときましょう！

2022-05-04 09:09 UTC, tak848 commented on user/views.py
> +        return super().form_invalid(form)
特に意味なさそうなので消しましょう！

2022-05-04 09:09 UTC, tak848 commented on user/views.py
> +    template_name = 'user/profile.html'
ログイン必須にしなかった意図はありますか？

2022-05-04 09:09 UTC, tak848 commented on user/views.py
> +        return response
登録時にログインもする親切仕様でgood!
ここではuserをformのデータからもう一度認証して引っ張ってきていますが，[こいつ](https://docs.djangoproject.com/ja/4.0/ref/class-based-views/generic-editing/#django.views.generic.edit.CreateView.object)を用いて，
```python
user = self.object
```
とするだけで，emailやpasswordでauthenticateしなくても作成したobjectを取得できます！

気が向いたらやってみてください！

2022-05-04 09:09 UTC, tak848 commented on user/tests.py
>  from user.models import User
今まで通り，user.modelsのUserを用いるか，
```python
User = get_user_model()
```
とするかのどちらかの使い方になると思うので，importは片方のみで良いはず！

あと，user.modelsを使用する場合は
`from .models import User`としましょう（前回のレビュー漏れっぽいです，すみません！）

2022-05-04 09:09 UTC, tak848 commented on user/tests.py
> +from django.test import Client
使っていなそうなので削除しましょう！

2022-05-04 09:09 UTC, tak848 commented on user/urls.py
> +    path('confirm/', views.LogoutConfirmView.as_view(), name='confirm'),
`confirm/`とするのは，urlの構造的にも何のconfirmかわからず混乱の元です。
とりあえず，logoutのconfirmだということが伝わるようなurlにしましょう。

（一応おまけの発展的なコメントしときます。
結局userに直接urlを打ってアクセスされたらconfirmする意味がないので，`logout/`に
* getでlogoutをするformのページを表示
* postされたらlogoutさせる（ブラウザから簡単にpostはできない）

とかするのが尚良し！な気がします。対応は不要ですが参考までに！）

2022-05-04 12:57 UTC, amoon46 commented on user/views.py
> +    template_name = 'user/profile.html'
プロフィールは他人の閲覧が可能であっても問題ないと考え、ログインは必須にしませんでした。（メールアドレスは消し忘れました。）

2022-05-04 13:19 UTC, amoon46 commented on user/urls.py
> +    path('confirm/', views.LogoutConfirmView.as_view(), name='confirm'),
ここの参考の部分がいまいち分からなかったので、名前の変更のみにしました。

2022-05-05 00:30 UTC, TAK848 commented on user/urls.py
> +    path('confirm/', views.LogoutConfirmView.as_view(), name='confirm'),
名前の変更のみでOKです！

一応，方針書いときますね！
logoutの処理自体は，django.contrib.auth のlogout関数を実行すればOKです。あとはrenderやredirectを自分で実装するのみです。
用意されたデフォルトのLogoutViewなどでは無理なので自分でviewを実装することになると思います。
普通のViewのクラスを継承し，
getメソッドでは確認画面をrenderしてあげて，
postメソッドではlogoutを実行してリダイレクトする処理を書いてあげれば実装は可能です。
（関数viewを使って，request.methodがpostかgetかで分岐させても同じ）

HTML内のformにはデータ無しで，`logout/`にsubmitだけするようにすれば完了となります。

2022-05-05 00:30 UTC, TAK848 commented on user/views.py
> +    template_name = 'user/profile.html'
OK！

2022-05-05 10:37 UTC, amoon46 commented
まず、commitのコメントの修正ですが誤って--amendを用いてしまい、git reset --hardによって元に戻しました。
よく分からなくなったので変更していません。

テストですが、最後の存在しないユーザーと他のユーザーですが、ログインしているアカウント以外でpostする方法が分からず実装できていません。

2022-05-05 10:39 UTC, amoon46 commented
<img width="1440" alt="test_logprofile" src="https://user-images.githubusercontent.com/74179935/166907282-7ee62ebe-8f20-45be-9654-5ec6618c37bf.png">

2022-05-05 10:40 UTC, amoon46 commented
<img width="1136" alt="git reflog" src="https://user-images.githubusercontent.com/74179935/166907473-a1e41d36-5984-42ab-9126-9d9196fe177c.png">

2022-05-06 00:01 UTC, TAK848 requested changes
> まず、commitのコメントの修正ですが誤って--amendを用いてしまい、git reset --hardによって元に戻しました。 よく分からなくなったので変更していません。

commitのコメントはそのままで良いです！プルリクそのもののタイトルを変えてください！ということです！（editで後からでも帰られます）一度プッシュしたcommitをいじると，強制上書きが必要になったりと危険なので避けましょう！
<img width="1262" alt="Screen Shot 2022-05-06 at 8 18 31" src="https://user-images.githubusercontent.com/41906969/167042148-23985d32-629b-4ab3-a4db-003baddeef83.png">

> テストですが、最後の存在しないユーザーと他のユーザーですが、ログインしているアカウント以外でpostする方法が分からず実装できていません。

`user/views.py`のコメントに書きましたのでご覧ください！
https://github.com/amoon46/TwitterClone/pull/2#discussion_r866400022

> 前回不明であったログインテストですが、（formにおいてのAuthenticationFormのデフォルトによるものなのか）postするデータのemailをusernameにすることで実行しています。テスト以外ではfiledとしてemailを認識しているので、どこに問題があるのかがわかりませんでした。

Good！usernameへの変更でOKです！あってます！
デフォルトのログインフォームでは，
https://github.com/amoon46/TwitterClone/blob/69af81267ce014c7b903c31896c204c1f6e61212/user/models.py#L82
のように設定しているので，usernameというnameのfieldに，メアドを入れることでログインができるようになっている仕様で，問題ないです！（サイトによっては，1つのinputにユーザーネームとメアドでもなんでも良いから入れて，みたいなログインページがあります。その時に代表のnameとしてusernameとしてるイメージ。設定をすればDjangoでもそんな感じにできます）
<img width="623" alt="Screen Shot 2022-05-06 at 8 24 37" src="https://user-images.githubusercontent.com/41906969/167042644-6d92f434-1d67-4855-a2b6-6043b044a11f.png">

2022-05-06 00:01 UTC, tak848 commented on .gitignore
> +.DS_Store
追記したこと自体はOKです！既に追加されてしまったDS_Storeが残ってしまっています。「gitignore 反映されない」で[google検索](https://www.google.com/search?q=gitignore%20%E5%8F%8D%E6%98%A0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84&tbm=&ie=utf-8&oe=utf-8&num=100&hl=&lr=&pws=1&filter=1)してみた結果などを参考に，一度追加されてしまった`.DS_Store`をどうにかして削除しましょう！
<img width="331" alt="Screen Shot 2022-05-06 at 8 36 27" src="https://user-images.githubusercontent.com/41906969/167043665-b8da99f0-ecb0-4c78-9b30-286c8a1d2f31.png">

2022-05-06 00:01 UTC, tak848 commented on user/views.py
> +    model = get_user_model()
ここで`get_user_model()`と書くのはあまり見ないので，SignupViewの上に
```python
User = get_user_model()
```
とかいて，ここでは`model = User`とするのが一般です。（僕も最終課題の時にそう習いました！）

ですが`tests.py`では`.models import User`としていて2種類が別ファイルで混在しているので，
1. get_user_model()で読み込む
2. (user).models import Userで直接読み込む
のどっちかに，全体を統一しましょう。（どちらも同義です）

2022-05-06 00:01 UTC, tak848 commented on user/views.py
> +        return super().get_object()
get_objectは，関数名の通り，返り値でDBから特定のレコードのobjectを指定してあげられる関数です。

この部分で，セッションからuserのpkを直接取得しているので，`urls.py`で
https://github.com/amoon46/TwitterClone/blob/69af81267ce014c7b903c31896c204c1f6e61212/user/urls.py#L14
のように書いていますが，urlにpkを書いている意味がないですね。

ここで，
```suggestion
    def get_object(self):
        return self.request.user
```
としてuserのobjectをそのまま返してあげれば，urls.pyのpkが完全に不要になります。
追加で，`update/`だと何をupdateするのかよくわからないので，いい感じのurlに変更してください！（前回抜けててすみません）

付随して，「url変えれば別のユーザーとして更新できてしまわないように」という意図のtestですが，原理的に「存在しないユーザーと他のユーザーのテスト」もこの実装なら不要になるので書かなくてOKです！

2022-05-06 00:01 UTC, tak848 commented on user/tests.py
> +        self.user = User.objects.create_user(email='test@gmail.com', password='Hogehoge777')
👍

2022-05-06 00:01 UTC, tak848 commented on user/tests.py
> +        self.login_user = self.client.login(email='test@gmail.com', password='Hogehoge777')
パッと見変数を使ってなさそうなので，self.userやself.login_userにわざわざ代入しなくてOK！

2022-05-06 00:01 UTC, TAK848 commented on user/tests.py
> +        self.login_user = self.client.login(email='test@gmail.com', password='Hogehoge777')
同様代入しなくてOK！

2022-05-06 07:54 UTC, amoon46 commented on user/views.py
> +        return super().get_object()
urlsの<int:pk>を削除してしまうとviewにおけるOnlyYouMixinのtest_funcがうまく機能しなくなるのですが、そちらはどのように対応したらいいでしょうか？

2022-05-06 09:51 UTC, TAK848 commented on user/views.py
> +        return super().get_object()
OnlyYouMixinは削除しても，Login必須ということはログイン中のユーザー本人（self.request.user）が必ず返されるので実質的に同じ意味になるので無くても良いんじゃないかな？と思います

---
url内にユーザーを指定する何かがあった方が良いともし思った場合は，
`profile/`を`user/profile/`とすると，ログイン中のユーザーであることを明記できます。（`user/`と単数で指定した場合はログイン中のユーザーを指すことが多いようです）
もし別のユーザーのprofileを見たい場合は，
`users/<pk>/profile/`のように指定するのが一般的です。（たくさんあるusersの中から，このユーザー！と1つ絞り込むイメージ）

2022-05-06 12:32 UTC, atsukihat commented
<img width="1436" alt="test" src="https://user-images.githubusercontent.com/74179935/167131883-1630c941-729b-4db7-a18d-af07c29f3bc6.png">

2022-05-07 00:12 UTC, TAK848 approved these changes
1点コメントした点直して貰えばLGTMです！！

2022-05-07 00:12 UTC, TAK848 commented on user/urls.py
> +    path('profile_update', views.ProfileUpdateView.as_view(), name='profile_update'),
```suggestion
    path('profile_update/', views.ProfileUpdateView.as_view(), name='profile_update'),
```
トレイリングスラッシュが抜けているので追加しときましょう！

2022-05-07 06:10 UTC, Akinori13 requested changes
とてもよくできています。
- 画面遷移ができないので、それぞれの画面で遷移できるようにしくてください。例えばログアウトをどのページからでもできるように。
- Userのプロフィールは他のユーザーのものも閲覧できるようにしてください

2022-05-07 06:10 UTC, Akinori13 commented on templates/user/profile.html
> +            <td>{% if user.introduction %}{{ user.introduction }}{% else %}未設定{% endif %}</td>
linebreaksbrを使ってみましょう

2022-05-07 08:21 UTC, amoon46 commented on templates/user/profile.html
> +            <td>{% if user.introduction %}{{ user.introduction }}{% else %}未設定{% endif %}</td>
画面遷移ですが、base.htmlにおいてログインが認証されていないとnavbarに表示されない仕様にしていますがどうでしょうか？（認証してないと結局ログイン画面に飛ばされるため）
ご指摘の画面遷移の認識と自分の認識が合っているかはわかりませんが。

profileの部分のログイン認証を削除しました。

2022-05-13 10:12 UTC, amoon46 commented
pkを加えて他のユーザーのも閲覧可能にしました。
画面遷移はログイン状態では可能になるようにしています。
テストの部分のuserが存在しない場合は、formにデータを送る方法が分からなかったため、実装できていません

2022-05-15 05:57 UTC, Akinori13 requested changes
かなり良いです。数点コメントしました

2022-05-15 05:57 UTC, Akinori13 commented on user/views.py
> +    def get_success_url(self,  **kwargs):
```suggestion
    def get_success_url(self):
```

2022-05-15 05:57 UTC, Akinori13 commented on user/views.py
> +    def test_func(self, **kwargs):
```suggestion
    def test_func(self):
```

2022-05-15 05:57 UTC, Akinori13 commented on user/tests.py
> +        pass
argを存在しないユーザーPKで送信してください。例えばUser(PK=1)、User2(PK=2)がいるときに、PK=3で送るがテスト事項になります。

2022-05-15 05:57 UTC, Akinori13 commented on user/views.py
> +        user = User.objects.get(pk=pk)
get_object_or_404

2022-05-15 14:47 UTC, amoon46 commented on user/views.py
> +    def test_func(self, **kwargs):
この変更はUpdateViewやUserPassesTestMixinにpkを渡したりするための機能が備わっているため、可変長位置引数を使う必要がないという認識であってますか？

2022-05-15 15:04 UTC, amoon46 commented on user/tests.py
> +        pass
<img width="1362" alt="test" src="https://user-images.githubusercontent.com/74179935/168479662-568d5af1-9c9f-44ff-b23f-9ac23c5505ee.png">

2022-05-15 15:09 UTC, amoon46 commented on user/tests.py
> +        pass
実際にテストにおいて、args=[3]を試した際にUserが存在していないのでformを送ることが叶わないということで前回質問させていだだいていました。分かりづらくて申し訳ないです🙇
出来れば、もう少し詳しく教えていだだけると嬉しいです！

2022-05-15 15:14 UTC, amoon46 commented
profileのurlにpkを変更することで他の人のprofileに移動することができるようになりました。
ただ、他人のprofileの画面にいる状態でnavbar（自分のprofileに飛ぶことを前提として作ったと考えている)を押すとurlのpkの変更が起きず、他人のprofileから移動できません。
これは、このままの仕様でも大丈夫なのでしょうか？

2022-05-17 07:44 UTC, Akinori13 commented on user/tests.py
> +        pass
申し訳ないです！！！
get_object_or_404で実装して、ユーザーが存在しない時に404を返すかテストしてもらいたいです！！

2022-05-18 08:14 UTC, Akinori13 commented on user/views.py
> +    def test_func(self, **kwargs):
`self.kwargs["pk"]`で取得できるので、使う必要がないです！！
django.views.generic.base.pyを見るとよいかもしれないです！

2022-05-18 09:05 UTC, amoon46 commented
<img width="1431" alt="test" src="https://user-images.githubusercontent.com/74179935/169001990-64d7d5c0-7e1d-4711-bd35-456917f7d7d3.png">

2022-05-18 09:06 UTC, amoon46 commented
テストの変更ですが、get_object_or_404の実装が上手くいかなかったため、別の方法で404のステータスコードが返ってくることを確認してます。

2022-05-19 11:05 UTC, Akinori13 approved these changes

2022-05-19 11:05 UTC, merged