App/tweet
amoon46/TwitterClone pull request #3
Opened 2022-05-24 08:32 UTC by amoon46

tweet, follow, like機能を実装しました。
ところどころ最終課題テスト項目要件整理と少し違うところもあります。

test機能は全部は実装できていません。また、redirect先を全てhomeとしているわけではないので、若干複雑になりもう少し時間がかかると思います。

実装の際にlikeやfollowing,followerのリストを表示するviewにおいて、DetailViewを用いれば良いのかListViewにすべきなのかなどの使い分け方がいまいち理解できませんでした。

2022-05-24 08:33 UTC, amoon46 commented
tweet, follow, like機能を実装しました。
ところどころ最終課題テスト項目要件整理と少し違うところもあります。

test機能は全部は実装できていません。また、redirect先を全てhomeとしているわけではないので、若干複雑になりもう少し時間がかかると思います。

実装の際にlikeやfollowing,followerのリストを表示するviewにおいて、DetailViewを用いれば良いのかListViewにすべきなのかなどの使い分け方がいまいち理解できませんでした。

2022-05-26 11:05 UTC, TAK848 requested changes
Djangoの機能がしっかり使えていて素晴らしいです！
テストに関しては，合図くれたら見ます！

## listview, detailviewについて
どの辺まで理解しているかがわからなかったのでざっくり書きます。実装見る限りは理解してそうな気がします。
- ListViewは，条件に合うレコードを全部表示するview（1ページあたりの表示数を指定して，paginationという機能を用いてページ分割することもできる）
- DetailViewは，urlに含まれるpkからレコードを一つ抽出して，そいつを表示するview

こんな感じ。[google検索](https://www.google.com/search?q=django%20listview%20detailview&tbm=&ie=utf-8&oe=utf-8&num=100&hl=&lr=&pws=1&filter=1)で一番上に出てきた[このページ](https://www.google.com/search?q=django%20listview%20detailview&tbm=&ie=utf-8&oe=utf-8&num=100&hl=&lr=&pws=1&filter=1)を見たり（多分見てそうだけど），Djangoのドキュメントやソースコードを眺めるのにtryしてみたりして，研究してみてください！

PostsのDetailViewを完成（リストと表示内容は同じでも良いです）させて導線（Tweetをタップしたらとか）を作るようにしてください！質問あればください！

一応，いいねについてはカウントのみで，いいねした人の一覧までは作らなくてOKです。

## Tweet機能について
- 注意事項にあるように，created_atを表示するようにしてください！

## いいね機能について
1. 【注意事項】にあるように，いいね・いいね取消機能はJavascriptから通信を行うFetchAPIで実装してください！
【キーワード】Model, Ajax, JSONResponse
2. 現状いいねをトグルする形式になっていますが，このままだと同じページを複数開き，同じ投稿にいいねした時どうなってしまうでしょう？工夫して改善してみてください！（Followも同様）

2022-05-26 11:05 UTC, tak848 commented on templates/tweet/follow_list.html
> +          <td>{% if user.nickname %}{{ user.nickname }}{% else %}I don't have a name yet. ({{user.pk}}){% endif %}</td>
```suggestion
          <td>{% if user.nickname %}{{ user.nickname }}{% else %}I don't have a name yet. ({{ user.pk }}){% endif %}</td>
```
他もちょくちょく空白が抜けてるので，チェックしてみてください！

2022-05-26 11:05 UTC, tak848 commented on templates/tweet/post_create.html
> +			<br>{% csrf_token %}
改行で無理やりあけるよりは，bootstrapで`mt-3`などで空けるのがおすすめです（今までのやつで見逃してたらごめんなさい！）
https://getbootstrap.jp/docs/5.0/utilities/spacing/#margin-and-padding

2022-05-26 11:05 UTC, tak848 commented on templates/tweet/post_delete.html
> +        </form>
見た感じ意図的なものっぽい（笑）ので内容はこれで良いですが，forで繰り返してみてはいかがでしょう？

2022-05-26 11:05 UTC, tak848 commented on templates/user/profile.html
> +
空行は0or1行にしましょう！（以下同様）

2022-05-26 11:05 UTC, tak848 commented on templates/tweet/follow_list.html
> +  {% endfor %}
どこか（or 全体）にユーザーページへのリンクを入れてあげましょう！

2022-05-26 11:05 UTC, tak848 commented on tweet/views.py
> +from django.views.generic import ListView, CreateView, DetailView,  UpdateView, DeleteView
```suggestion
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
```
謎の空白残ってます！

2022-05-26 11:05 UTC, tak848 commented on tweet/views.py
> +
現状で動いていて，動作としてはOKです👍

ですが課題の
【注意事項】・select_relatedやprefetch_relatedを用いて「N+1問題」を回避してください
が現状回避できていません。`get_queryset`をoverrideして，以下のボトルネックを修正してください。

1. テンプレート内でfor文でそれぞれのユーザーのデータ(item.user...)を取得していて，SQLがそれぞれ発行されており，N+1問題のボトルネックになっています。
2. テンプレート内のfor文でそれぞれのいいね（item.like...)を毎回取得していて，そちらもN+1問題のボトルネックになっています。

↓django-debug-toolbarを用いると，ページごとに実行されたSQLを表示できます。テンプレートのどこで同じようなクエリが発行されてしまっているかわかるので，参考にしてください！（django-debug-toolbarで表示しました）
<img width="970" alt="Screen Shot 2022-05-26 at 19 40 59" src="https://user-images.githubusercontent.com/41906969/170472467-cefc5d49-9712-4dd7-9156-fe7226571484.png">
↓10similarobjectsの箇所
<img width="749" alt="Screen Shot 2022-05-26 at 19 41 12" src="https://user-images.githubusercontent.com/41906969/170472483-bd9f23b3-23cd-42d2-a8a7-3c9116185090.png">
↓9similarobjectsの箇所
<img width="854" alt="Screen Shot 2022-05-26 at 19 41 23" src="https://user-images.githubusercontent.com/41906969/170472495-f475cf92-5a81-459d-b2a0-ec6699b355b5.png">

2022-05-26 11:05 UTC, tak848 commented on tweet/views.py
> +        return Post.objects.filter(user=self.request.user)
同様に，N+1問題を修正してください！

2022-05-26 11:05 UTC, tak848 commented on user/views.py
> +        context['Post'] = Post.objects.filter(user=user)
1. `Post`->`post`としましょう！
2. 同様に，N+1問題を修正してください！

2022-05-26 11:05 UTC, tak848 commented on tweet/views.py
> +        return redirect('user:profile', pk)
実装はOK👍

現状フォロー・フォロー解除をトグルする形式になっていますが，このままだと同じページを複数開き，同じ人にフォロー/フォロー解除した時どうなってしまうでしょう？工夫して改善してみてください！（いいねも同様）

2022-05-26 11:05 UTC, tak848 commented on tweet/models.py
> +    created_at = models.DateTimeField(default=timezone.now)
created_atに関しては，default値よりは，`auto_now_add`を使う実装が多いです！

2022-05-26 11:41 UTC, amoon46 commented on templates/tweet/follow_list.html
> +          <td>{% if user.nickname %}{{ user.nickname }}{% else %}I don't have a name yet. ({{user.pk}}){% endif %}</td>
同様のミスをいくつもしていましたが、確認できたところは直しました。

2022-05-26 12:38 UTC, amoon46 commented on templates/tweet/post_delete.html
> +        </form>
for文での実装も考えたのですが、htmlだとリスト、辞書、タプル要素ありきのものしか見つけることができず、複数行に渡って同じ記述になってしまいました。

2022-05-27 01:34 UTC, TAK848 commented on templates/tweet/post_delete.html
> +        </form>
ベストプラクティスかはわかりませんが， https://e-tec-memo.herokuapp.com/article/168/ とか参考にしてみてください！
[django template for range](https://www.google.com/search?q=django%20template%20for%20range&tbm=&ie=utf-8&oe=utf-8&num=100&hl=&lr=&pws=1&filter=1)で調べてみました

2022-05-27 07:40 UTC, amoon46 commented on templates/tweet/post_create.html
> +			<br>{% csrf_token %}
確認できるところはbrを削除しました。

2022-05-27 07:51 UTC, amoon46 commented on templates/tweet/post_delete.html
> +        </form>
普通の機能に戻して実装しています（笑）

2022-05-27 07:59 UTC, amoon46 commented on templates/tweet/follow_list.html
> +  {% endfor %}
これは、nicknameからそのユーザーに飛べるようにするという意味ですか？
それとも、元のユーザーのprofileに戻れるようにするという意味でしょうか？

2022-05-27 09:00 UTC, amoon46 commented on tweet/views.py
> +        return redirect('user:profile', pk)
すいません、このトグルする形式において複数ページ開いても更新すればきちんと動作するのですが、どの辺が問題でどの辺を改善すればいいかがいまいちわかりません。

2022-05-27 10:21 UTC, TAK848 commented on tweet/views.py
> +        return redirect('user:profile', pk)
ユーザー目線で考えた時の問題です。

一方の画面でフォローボタンを押すとします。→正常にフォローできます。
もう一方の画面（別のタブやデバイスなど）でもフォローボタンがあり，ユーザーはフォローをしていなかったと思って再度フォローしようとフォローボタンを押します→フォローしたつもりなのに，DB上ではフォローされていることからフォローが解除されます。（=ユーザーから見ると，フォローボタンを押したつもりなのにフォローボタンがまた出てきて混乱します。この場合，トグルするのではなく，既にフォローしていることからそのままアンフォローボタンを表示した画面を返すのが適切）

みたいなことが起こります。（丁寧に説明しようとしてわかりにくくなってたらすみません！）
viewを増やしても良いので対処してみてください！

2022-05-27 10:21 UTC, TAK848 commented on templates/tweet/follow_list.html
> +  {% endfor %}
そのユーザーに飛べるようにです！aタグをどこかにつけてくれれば良いです！

2022-05-27 10:21 UTC, TAK848 commented on templates/tweet/post_delete.html
> +        </form>
了解です笑

2022-05-27 10:24 UTC, TAK848 commented on templates/tweet/follow_list.html
> +  {% endfor %}
テンプレートのいろいろな箇所でPostを表示しているので，変更箇所が多岐に渡って大変そうな気がします。post.htmlなどを作ってコンポーネント化するとさらに良いかもですね。これに関してはお任せします！

2022-05-28 06:09 UTC, amoon46 commented on templates/tweet/follow_list.html
> +  {% endfor %}
了解です。
follow_list.html以外はhome画面のpostにのみuserへのリンクになり、そちらは実装しているので上記の部分のみの変更してます。

2022-05-28 14:38 UTC, amoon46 commented on tweet/views.py
> +        return redirect('user:profile', pk)
followとunfollowのviewを別々に分けることで、フォロワーがいる時といない時の対処をifとelseとでの二者択一にする必要がなくなる。つまり、フォローがいる(いない)ときにpassを用いることで、機能と画面の整合性を保つことができるという認識でいいでしょうか？

pushした時に自分の考えを忘れないように、実装した後すぐにコメントしているのでcommitの際にわかるようになっていると思います。

2022-05-29 00:19 UTC, TAK848 commented on tweet/views.py
> +        return redirect('user:profile', pk)
OKです👍
ユーザー側から「トグルして」とお願いするのではなく，「フォローして」「解除して」のようにrequestするようにしましょう！

2022-06-02 05:17 UTC, amoon46 commented
現在followtestの実装中で、期待しているresponse.code=302のところで405が返ってきてしまいどうしても解決することができなかったので一度pushしたので、解決策を伺いたいです。

まだ実装していない機能
・いいね機能のFetchAPI（トグルの問題なども考慮して、modelにおいて現在はpostの中にlike機能を設けているが新しくlikeもclassを作成するか検討中）
・DetaileView(created_at 実装はすぐできるだろうが、いいね機能の後に実装したい。)
・残りのtest

2022-06-02 12:58 UTC, TAK848 requested changes
> 現在followtestの実装中で、期待しているresponse.code=302のところで405が返ってきてしまいどうしても解決することができなかったので一度pushしたので、解決策を伺いたいです。

該当箇所のviewにヒント書きました〜！

fetch APIについては，ちょっとjavascriptを書くことになると思います。ベストな方法は，viewを作るorHTTP methodをうまく使ってみるかになると思いますが，Djangoのtemplateを使うので無理なく前者が個人的には楽じゃないかな？と思います。

2022-06-02 12:58 UTC, tak848 commented on config/settings.py
> +    'debug_toolbar',
紹介しといてすみません！
一応，PR出す時は削除しときましょう！
（1次レビュー終わる前でも良いです！）

2022-06-02 12:58 UTC, TAK848 commented on tweet/urls.py
> +    path('post/<int:pk>/delete/', views.DeletePost.as_view(), name='post_delete'),
```suggestion
    path('posts/<int:pk>/delete/', views.DeletePost.as_view(), name='post_delete'),
```
他と一応合わせときましょー

2022-06-02 12:58 UTC, TAK848 commented on user/views.py
> +        user = get_object_or_404(User, pk=pk)
DetailViewは，勝手にモデルから一致するpkのobjectを引っ張ってきて`self.object`に格納してくれます。そのため，こうするとDetailViewの内部処理とここで2重にuserを取得してしまうので，
```python
user = self.object
```
だけでいくと高速化できます。404も勝手に返してくれます

2022-06-02 12:58 UTC, TAK848 commented on tweet/views.py
> +        return redirect('user:profile', pk)
httpのステータスコードだけでも，ある程度意味を特定できるケースがあり，今回のテストで405が帰ってくる件はまさにこれに該当します！
HTTP 405で調べてみて，viewでのget実装とtestで何をしてるかを比較して考えて見てください！
怪しかったら，HTTPのメソッド（GETとPOSTを最低限！）と，ステータスコードを軽く調べて見てください！

2022-06-02 12:58 UTC, TAK848 commented on user/views.py
> +        context['post'] = Post.objects.filter(user=user).select_related('user').prefetch_related('like')
good!

2022-06-02 12:58 UTC, TAK848 commented on tweet/views.py
> +        return Post.objects.all().select_related('user').prefetch_related('like')
good!

2022-06-02 12:58 UTC, TAK848 commented on tweet/views.py
> +        return Post.objects.filter(user=self.request.user)
使わなそうだったら削除お願いします〜！

2022-06-04 09:10 UTC, amoon46 commented
非同期通信の機能を実装していて困っています。
現状としては、staticにjsのコードを書きました。htmlもそれに対応する形にしています。(とりあえずhomeのみ)
home画面においては一度だけならいいね機能(like, unlike)を作用させることができています。(管理者権限の画面で確認済み)
ただ、もう一度押すと404のコードが返ってきてしまい、うまくいきません。これはLikeView,UnlikeViewにおけるadd,removeが非同期で送れていないことが原因ではないかと考えています。

調べたところ、like機能は基本的にmodelの段階でpostのフィールドとして組み込むのではなく、新しいモデルとして作成しているものがほとんどのように思います。その場合はviewにおいてpostとforeingkeyでつながっているlikeを削除することで実装しています。

現状のモデルのままでうまくいかないので、新しくlikeモデルを作成することも考えています。（ただ、他の部分への影響も大きいので変更する箇所が多々ある。）
アドバイスなどをいただけるとありがたいです。

2022-06-04 12:35 UTC, TAK848 commented
404はパスが間違っていることが多いです！検証で，アクセスしているURLをよく見てみてください！ネットワークのとこから見られます！
↓例
<img width="607" alt="Screen Shot 2022-06-04 at 21 30 31" src="https://user-images.githubusercontent.com/41906969/171999078-96bc94e8-06ef-4c82-a6b7-d0327079f1e7.png">

 と思ったら解決したっぽい？よかったです！

2022-06-07 06:14 UTC, amoon46 commented
ajaxを用いて非同期通信とテストを実装しました。
いいねの数において、ボタンが押されたとき(post)のみ表示される実装になっています。押さないと数を確認できない。また、profileにおけるuserがいいねした投稿の数も同様に非同期ではない。（ページを読み込むまで変更されない）ただ、最終課題の要件自体は満たしていると考えています。

（余談）
以前「detailviewとlistviewの違いがわからない」という質問をしたのですが、上記のcommitで削除したlike_listにおいてはListView, followingとfollowersのリストにおいてはDetailViewを使用しています。元々は全てListViewを使用していたのですが、listが表示されたページから、そのリスト元のユーザーのprofileに戻る際に必要なuser.pkを取得するためにDetailViewに変更しました。ListVeiwでは「user.pk=request.user.pk」となってしまう。ただ、like_listのみDetailViewに変更すると上手くいかなかった。上記の様な点において、どういった違いがあるのか分からないという趣旨の質問でした。

2022-06-08 08:04 UTC, TAK848 requested changes
お疲れ様です！コメントしました！

いいねのカウントですが修正すれば表示できると思いますよ！

2022-06-08 08:04 UTC, tak848 commented on templates/tweet/top.html
> +            <span>{{ post.like.count }}</span>
```suggestion
            <span>{{ item.like.count }}</span>
```
typo?

2022-06-08 08:04 UTC, tak848 commented on templates/user/profile.html
> +              <span>{{ post.like_set.count }}</span>
typo?

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +class Like(LoginRequiredMixin, View):
ViewClassは〇〇Viewとしましょう（他も）

2022-06-08 08:04 UTC, tak848 commented on tweet/urls.py
> +    path('followers/<int:pk>/list/', views.UserFollowersList.as_view(), name='followers_list'),
follow系ってtweet appというよりどちらかというとuserの方な気が？（そのままでも良いです）

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +                login_user.followees.add(user)
not使って行数減らせそう

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +        if (user != login_user):
条件一つの時に括弧をつける必要はないです

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +                pass
必要？

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +            messages.warning(request, 'This user do not exist')
get_object_or_404に引っ掛かったらそれより後ろは実行されないので不要？

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +        if ((user != login_user) and (user != 404)):
外側の括弧は不要消しましょう

2022-06-08 08:04 UTC, tak848 commented on tweet/views.py
> +
変に2行空いているので消しましょう

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        time.sleep(0.1)
確認です！time.sleepを入れた意図は？

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.post = Post.objects.create(text='テストを試しています。', user=self.user1)
user1に習って合わせましょう

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.client.post(self.url_post_follow3)
各userのmanytomanyに直接追加する方法を調べて，準備をclient.postを使って行うのはやめましょう！
（テスト対象はUserProfileのgetで，followやfollowerへのpostがメインではない）

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.user2 = User.objects.create_user(email='hogehoge@gmail.com', password='Hogehoge777')
使ってますか？

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.assertTrue(Post.objects.exists())
setUpにassert必要？

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.url_post_follow1 = reverse('tweet:follow',  kwargs={'pk': self.user1.pk})
順番？

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        self.url_post_unfollow1 = reverse('tweet:unfollow',  kwargs={'pk': self.user1.pk})
順番？

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +            followees=self.user2).exists())
clientを使わずに足しましょう

2022-06-08 08:04 UTC, tak848 commented on tweet/tests.py
> +        response = self.client.post(self.url_like, HTTP_X_REQUESTED_WITH='XMLHttpRequest')
`HTTP_X_REQUESTED_WITH='XMLHttpRequest'`は必要？

2022-06-08 08:04 UTC, TAK848 commented on tweet/tests.py
> +        self.client.post(self.url_like, HTTP_X_REQUESTED_WITH='XMLHttpRequest')
clientを使わずに準備しましょう

2022-06-08 08:08 UTC, TAK848 commented
ListViewとDetailViewの話ですが，そのことでしたら今回の場合，`get_queryset`を使えば`pk`引っ張りつつ用件を満たせると思うので調べてみてください！

2022-06-08 14:18 UTC, amoon46 commented on tweet/tests.py
> +        time.sleep(0.1)
postオブジェクトを一気に複数作るため感覚を開けるというつもりで行ったと思います。
ただ今見返してみると、同じ理屈でuserなどにも行う必要があるため消すか全てに書くか統一するべきでした。

2022-06-09 11:04 UTC, TAK848 commented on tweet/tests.py
> +        time.sleep(0.1)
一気に作る目的だけなら不要です！

pkの順序が絶対保証されないとどうしてもまずいテストとかでのみつければ良いかな，と思います

2022-06-10 13:25 UTC, atsukihat commented on tweet/tests.py
> +        response = self.client.post(self.url_like, HTTP_X_REQUESTED_WITH='XMLHttpRequest')
非同期通信かどうかを判断するために必要と考えたので書いています。
コメントの内容からいらない様でしたので削除してます。

2022-06-10 23:12 UTC, TAK848 requested changes
test1点直してもらえればLGTMです！

2022-06-10 23:12 UTC, tak848 commented on tweet/tests.py
> +        self.user1.followees.add(self.user3)
👍
ちなみに
```python
        self.user1.followees.add(self.user2, self.user3)
```
と1行にまとめることもできます(修正不要)

2022-06-10 23:12 UTC, TAK848 commented on tweet/tests.py
> +        self.assertEqual(json.loads(response.content)['liked'], True)
setUpには不要です（もしチェックするなら`test_xx`を新たに作ってそこで！）

2022-06-11 03:09 UTC, TAK848 reviewed
LGTM!!

2022-06-11 03:10 UTC, TAK848 approved these changes

2022-06-13 07:56 UTC, merged